export const REDACT_USER = 'REDACT_USER'
export const ADD_USER = 'ADD_USER'
export const DELETE_USER = 'DELETE_USER'
export const SHOW_MODAL = 'SHOW_MODAL'
export const HIDE_MODAL = 'HIDE_MODAL'
export const USERS_ERROR = 'USERS_ERROR'
export const DELETE_USERS_ERROR = 'DELETE_USERS_ERROR'
export const SHOW_MALE = 'SHOW_MALE'